site_name: Xentis' Steel Compendium
site_url: https://steelcompendium.io

copyright: The Draw Steel Compendium is an independent product published under the DRAW STEEL Creator License and is not affiliated with MCDM Productions, LLC. DRAW STEEL © 2025 MCDM Productions, LLC.

theme:
   name: 'material'
   palette:
      scheme: slate
      primary: black
      accent: blue
   logo: Media/favicon.ico
   favicon: Media/favicon.ico

# Extensions
markdown_extensions:
   - footnotes
   - attr_list
   - md_in_html
   -  pymdownx.tasklist:
         custom_checkbox: true
   - def_list
   - pymdownx.critic
   - pymdownx.caret
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.tilde
   - pymdownx.superfences
   -  pymdownx.emoji:
         emoji_index: !!python/name:material.extensions.emoji.twemoji
         emoji_generator: !!python/name:material.extensions.emoji.to_svg
   -  toc:
         permalink: true
         toc_depth: 1-8

plugins:
   - search
   - roamlinks

extras:
   analytics:
      provider: google
      property: G-PMF9SHHXNY

extra_css:
   - stylesheets/extra.css
   - stylesheets/custom_font.css
